### ISSUE TITLE
Pipes, By Themselves, Don't Output To Machines

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#608] opened 2019-03-04 22:36 UTC
This is essentially expanding upon #603 . 
When you have a pipe filled with a fluid next to a machine, the fluid from the pipe by default doesn't go to the machine
![image](https://user-images.githubusercontent.com/25333164/53767215-5ebe5980-3ed5-11e9-97d0-fafa2eada414.png)
![image](https://user-images.githubusercontent.com/25333164/53767221-63830d80-3ed5-11e9-8eb1-f6a2d9637c30.png)
 It only does so when a Pump forces is it out
![image](https://user-images.githubusercontent.com/25333164/53767252-82819f80-3ed5-11e9-9184-4ea72995f63d.png)

 And no, the issue is not related to the machines themselves as it works perfectly fine with other mods' pipes, such as fluiducts
![image](https://user-images.githubusercontent.com/25333164/53767300-acd35d00-3ed5-11e9-9e7e-dcbea891c072.png)

 This issue is especially problematic early on, when pumps aren't so easy to make.

**Comment by 15103875d** [comment] 2019-03-05 03:18
Many thanks.
The pumps shown in the screenshot uses as a cover plate? The JEI told me the pump has an argument called voltage? But I tried it can work without electricity. Is it a mistake by JEI or the mod?

**Comment by Archengius** [comment] 2019-03-06 20:19
Duplicate of #603.

**Closed by Archengius** 2019-03-06 20:19 UTC
