### ISSUE TITLE
Weird surface rocks

### ISSUE THREAD

**Issue by KrisBigK** [GregTechCE/GregTech#237] opened 2018-07-20 09:38 UTC
![2018-07-20_16 28 20_2](https://user-images.githubusercontent.com/34199560/42995444-80f271fc-8c43-11e8-828d-1f48b17feb22.png)
![2018-07-20_16 29 32_2](https://user-images.githubusercontent.com/34199560/42995501-a2423644-8c43-11e8-92ac-b3f97a06e327.png)
![2018-07-20_19 07 10](https://user-images.githubusercontent.com/34199560/42999409-38cfd2ae-8c50-11e8-960c-e26de2b43ee8.png)
![2018-07-20_19 14 13](https://user-images.githubusercontent.com/34199560/42999677-501b8740-8c51-11e8-8350-77c30b871eaa.png)

Also, Placing lava next to the block will cause the lava to become obsidian.

**Comment by Archengius** [comment] 2018-07-28 15:44
there is nothing can be done about last - this will always persist

**Comment by Archengius** [comment] 2018-08-30 20:13
duplicate of #202

**Closed by Archengius** 2018-08-30 20:13 UTC
Labels: type: bug
