### ISSUE TITLE
Nugget Generation

### ISSUE THREAD

**Issue by ScienceDrummer** [GregTechCE/GregTech#248] opened 2018-07-26 18:51 UTC
I was playing around in Aether Legacy v3.0 and I found metal nuggets to be generating on top of clouds. I also found them to spawn on top of giant mushrooms.
![2018-07-25_18 11 44](https://user-images.githubusercontent.com/31962430/43282141-f7a1fc6e-90da-11e8-871b-28219297611b.png)
![2018-07-25_18 13 16](https://user-images.githubusercontent.com/31962430/43282142-f7b61eb0-90da-11e8-955e-473087f8bea6.png)
![2018-07-25_18 29 55_2](https://user-images.githubusercontent.com/31962430/43282143-f7c75982-90da-11e8-99f6-57be3bec1c73.png)

**Comment by Exidex** [comment] 2018-07-28 15:38
Duplicate of #237

**Closed by Exidex** 2018-07-28 15:38 UTC
Labels: type: duplicate
