### ISSUE TITLE
Plasma turbines randomly not detecting fuel inside input block.

### ISSUE THREAD

**Issue by WhiteVorest** [GregTechCE/GregTech#939] opened 2019-08-15 14:13 UTC
I have created 12 plasma turbines at the same time, supplied with helium plasma and 2 of them do not detect fuel in input block despite said block being full. Tried with new input of different sizes (from ULV to ZPM), freshly crafted controller, different rotor holders and turbines, completely dismantling all blocks and reforming structure. All 12 turbines follow exactly same design. (I'm playing Omnifactory modpack)
![2019-08-15_15 43 54](https://user-images.githubusercontent.com/54145154/63100446-618aa380-bf77-11e9-8616-c98e36c1ab21.png)
![2019-08-15_15 54 11](https://user-images.githubusercontent.com/54145154/63100447-618aa380-bf77-11e9-9aff-5e37ec5e8b33.png)
![ffsaefasdv](https://user-images.githubusercontent.com/54145154/63100540-91d24200-bf77-11e9-9900-1bbcc6ab57c1.JPG)

**Comment by Blood-Asp** [comment] 2019-08-15 14:22
I had this before. The cause was invisible light blocks from the lantern in front of the turbine failing the rotor check. So the error message has to be improved and ideally the lantern light has to be detected as air.

**Comment by leagris** [comment] 2019-08-15 15:10
One may wonder why lessons are not learned: https://github.com/GregTechCE/GregTech/pull/458

**Comment by WhiteVorest** [comment] 2019-08-15 15:19
Blood-Asp, thank you so much for this! It was driving me mad and I indeed have lightblocks all over place - Feral Flare Lanterns.

**Comment by Archengius** [comment] 2019-08-15 19:53
probably because that code was written way before both issues and wasn't fixed by your PR

**Closed** 2019-08-18 07:40 UTC
