### ISSUE TITLE
Console Spam And Server Performance

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#276] opened 2018-08-23 14:45 UTC
Well, let's start with the simple stuff.
- Pumps spam NPEs in the console when they aren't active. I get that they check every tick if they can run, but they shouldn't print a NPE to the console when they can't
- We (this is on 2 different servers) sometimes get `[Error] [FML]: NetworkDispatcher exceptionio.netty.channel.unix.Errors$NativeIoException: syscall:writev(..) failed: Broken pipe    at io.netty.channel.unix.FileDescriptor.writeAddresses(..)(Unknown Source) ~[FileDescriptor.class:?].` spammed in the console.
- (additionally, the crafting recipe removal method GTCE uses makes forge think it's not intended, but that's just during loading so it doesn't matter too much)

 And then there is performance. Tps is usually about 20, which is great, however the main issues are on the clients' side. To my understanding, when a client is near multiple active machines (probably due to all the power being transferred), the server tries to send a large amount of packets to them, eventually causing them to be kicked from the server with
![image](https://user-images.githubusercontent.com/25333164/44532873-78940e00-a6f4-11e8-84e2-4bb98d325c61.png)
 There are also noticeable memory leaks that cause the clients' fps to drop significantly https://pastebin.com/kxCreBge While on SP everything is fine, people tend to play packs on MP and this makes that quite difficult.

**Comment by Archengius** [comment] 2018-08-23 18:47
> Pumps spam NPEs in the console when they aren't active. I get that they check every tick if they can run, but they shouldn't print a NPE to the console when they can't
cannot reproduce. Attach fucking logs to issues.
> We (this is on 2 different servers) sometimes get [Error] [FML]: NetworkDispatcher exceptionio.netty.channel.unix.Errors$NativeIoException: syscall:writev(..) failed: Broken pipe at io.netty.channel.unix.FileDescriptor.writeAddresses(..)(Unknown Source) ~[FileDescriptor.class:?]. spammed in the console.
Not related to GTCE in any way.
> (additionally, the crafting recipe removal method GTCE uses makes forge think it's not intended, but that's just during loading so it doesn't matter too much)
Can you read? There is message explaining that being printed before FML warnings begin.
> To my understanding, when a client is near multiple active machines (probably due to all the power being transferred), the server tries to send a large amount of packets to them, eventually causing them to be kicked from the server with
Needs further investigating. Submit separated issue with logs and full description.
> There are also noticeable memory leaks that cause the clients' fps to drop significantly https://pastebin.com/kxCreBge While on SP everything is fine, people tend to play packs on MP and this makes that quite difficult.
Fixed in latest commit

**Closed by Archengius** 2018-08-23 18:47 UTC
