### ISSUE TITLE
[BUG] Thaumic Augmentation Warded Chest Causes GTCE Chests To Go Transparent, Mayhaps Other Mods As Well.

### ISSUE THREAD

**Issue by DarkAmbientNoise** [GregTechCE/GregTech#1235] opened 2020-09-08 01:53 UTC
**Describe the bug**
Having Thaumic Augmentation included in the pack and at other times, some other mods (Unknown, can't seem to catch the others yet), causes texture bugs with some GTCE blocks, such as chests to go entirely transparent. Hitbox and all functionality remain, including HUD tools like Waila.

**Versions**
Forge: 14.23.5.2854
GTCE: 1.12.2-1.10.1.557
CodeChicken Lib 1.8.+: 1.12.2-3.2.3.358-universal
**Modpack:** None: Minimum to run GTCE and attempt to catch this bug.
**Addons:**
Baubles 1.12-1.5.2
JEI 1.12.2-4.16.1.301
Thaumcraft 1.12.2-6.1.BETA26
Thaumic Augmentation 1.12.2-1.1.19

**Setup**
Playing Solo Super Flat World. New World as a testing environment.

**Steps To Reproduce**
1) Place down one of each of GTCE chests.
2) Place down Thaumic Augmentation's "Warded Chest"
3) Done. Immediate results.

**Expected behavior**
Expect All blocks to still be fully visible.

**Screenshots**
1. Screenshot Immediately after the described steps (Shadows for chests remain)

![2020-09-07_19 51 35](https://user-images.githubusercontent.com/12950685/92422984-f644de00-f144-11ea-9fe6-39d405e96a73.png)

2. Hitboxes and functionality remain.

![2020-09-07_19 58 01](https://user-images.githubusercontent.com/12950685/92423011-0a88db00-f145-11ea-8924-df08dd2271b3.png)
![2020-09-07_19 58 07](https://user-images.githubusercontent.com/12950685/92423013-0c529e80-f145-11ea-9f97-881b07b45333.png)

**Additional context**
Removing Thaumic Augmentation Immediately resolves the issue. Placing it in GTCE bug tracker as this issue merely seems to be bugging out with other mods installed, not that GTCE is directly the cause. I have seen this happen with other blocks from other mods (placing lots of things, to come back and find this issue, even without placing a Warded Chest) So I assume, it may be on GTCE's end. It's sometimes hard to narrow things down with hundreds of mods. 

Edit: It seems that Thaumcraft's Hungry Chest may also be causing lighting glitches on CTCE chests as well, they all change to be about 15% brighter than they normally appear. Unfortunately Thaumcraft 6 on 1.12.2, is likely forever stuck in beta to my understanding with Azanor no longer actively developing it.

**Comment by LAGIdiot** [comment] 2020-09-09 16:16
Thank you for reporting this issue. This one is caused by other mods leaving unfinished business in rendering pipeline. Most likely because they don't clean it properly after usage. And there is not much for us to do with it. So please report this bug to Thaumic Augmentation as owner of said problematic block. And please link their issue to this.

**Comment by TheCodex6824** [comment] 2020-09-10 00:14
Dev of TA here, I looked into this earlier and was able to reproduce the chests disappearing without my mod or any TC stuff. It seems that any FastTESR that uses the Forge animation system causes that to occur, which I tested using the Forge debug mod. If you want to test it yourself, the debug mod should put a few animation test blocks at the bottom of the building blocks tab in creative mode, when placed they cause the disappearing chest issue. I'm not sure if the animation system is the exact cause of all of this, but I know that works reliably.

But at this point because I reproduced it with the forge debug mod I don't think it's my mod. And my block is a FastTESR, so it doesn't touch GL state or anything, and Forge handles setting up the buffer and sending off the quads.

**Comment by LAGIdiot** [comment] 2020-09-10 07:36
Thank you for reaching to us. I will definitely try reproductions steps that you provided us with and see what I can do with it.

**Comment by ALongStringOfNumbers** [comment] 2021-01-19 01:04
I reproduced this on GTCE 1.10.9.612, TC 6.1.Beta26, Thaumic Augmentation 2.0.13.

I tested this again on the newer GTCE version after #1373 was merged to see if the changes there would solve this issue as well, but the issue still happens. The reproduction case is the same as provided in the initial issue.

**Comment by DStrand1** [comment] 2021-01-19 02:17
This is perhaps not the best information, but I can also add to this that I had this same issue occur in Omnifactory ver. 1.2.2, which does not include the Thaumic Augmentation mod. Not sure if this has since been fixed in that particular case though, as #1373 may have fixed that already.

**Comment by CrafterKolyan** [comment] 2021-02-18 21:30
Confirming this issue on GregTech 1.11.3.640 and on GregTech 1.9.4 so #1373 doesn't fix it.

**Comment by CrafterKolyan** [comment] 2021-02-18 22:38
But it's working fine on 82ccbeec2333305252cff801ee0c839ca7f33da1 :-) Love `git bisect`

**Comment by CrafterKolyan** [comment] 2021-02-18 22:52
Found the first commit which reporuces this bug:
ba278fcd42374073b208695e35c60bdf1e43525c
Date:   Thu Mar 7 21:00:07 2019 +0700
    Reworked Chests. Changed appearance, audio and size. Closes #527.
    Fixed Material support for CraftTweaker.
    Added assembler recipe for frames.
    Bump version.

**Comment by CrafterKolyan** [comment] 2021-02-18 23:39
I don't know why but it's calling because `renderMetaTileEntity` is called instead of `renderMetaTileEntityDynamic`.

I can also admit that once these chests are not rendered they are not rendered in any other world which seems as somebody overrides us and the problem becomes global.

**Comment by CrafterKolyan** [comment] 2021-02-19 00:22
@TheCodex6824 Based on my observations (rendering breaks completely in other worlds) I can say that it's just something overriding us or classes of base Minecraft, so we don't get the expected logic. I personally think that the origin of problem is:

https://github.com/TheCodex6824/ThaumicAugmentation/blob/6c3a289e7d2b95a758767a9fdb7b20dc423c4503/src/main/java/thecodex6824/thaumicaugmentation/core/transformer/TransformerTCBlueprintCrashFix.java#L58-L61

You are overriding some function of `TileEntityRendererDispatcher` and I don't exactly know what do you want to get but I am pretty sure that this is the main problem because I do not understand how we got our `MetaTileEntityTESR` not called except if somebody just overriding code on the fly.

**Comment by TheCodex6824** [comment] 2021-02-19 00:32
> @TheCodex6824 Based on my observations (rendering breaks completely in other worlds) I can say that it's just something overriding us or classes of base Minecraft, so we don't get the expected logic. I personally think that the origin of problem is:
> 
> https://github.com/TheCodex6824/ThaumicAugmentation/blob/6c3a289e7d2b95a758767a9fdb7b20dc423c4503/src/main/java/thecodex6824/thaumicaugmentation/core/transformer/TransformerTCBlueprintCrashFix.java#L58-L61
> 
> You are overriding some function of `TileEntityRendererDispatcher` and I don't exactly know what do you want to get but I am pretty sure that this is the main problem because I do not understand how we got our `MetaTileEntityTESR` not called except if somebody just overriding code on the fly.

That code is not overriding anything *in* `TileEntityRendererDispatcher`, instead it is just finding the place in Thaumcraft code where it invokes a method in that class. That entire transformer is only patching *Thaumcraft* code to jump to some of my code to prevent a crash, it doesn't touch anything outside of Thaumcraft's ingame book (the Thaumonomicon).

One thing it would be helpful to look into - Forge itself has a test mod that implements some of the Forge features, including the animation system. A while back I was able to reproduce the chest disappearing issue using just that test mod. Checking if that is still the case could be a good lead.

**Comment by TheCodex6824** [comment] 2021-02-19 01:41
Can confirm that the blocks using the forge animation system in the forge test mod still cause the chests to disappear. This was recorded on a freshly cloned version of this mod with nothing added except for the forge test mod and buildcraft (because forestry kept crashing if I didn't put it in):


https://user-images.githubusercontent.com/33965527/108444996-8c804280-7253-11eb-9737-44de72280a9b.mp4

**Comment by ALongStringOfNumbers** [comment] 2021-03-16 21:10
> I don't know why but it's calling `renderMetaTileEntity` instead of `renderMetaTileEntityDynamic`.

Going off of this report by @CrafterKolyan I changed the render call in `MetaTileEntityRenderer#renderBlock` in the first `if` statement to not always call `metaTileEntity.renderMetaTileEntity`, but first check if the MTE was an instanceof `IFastRenderMetaTileEntity` and if it was I instead called that method instead of `renderMetaTileEntity`.

I did this because I noticed that the Chest overrides `renderMTE` but does not have anything in the method it overrides, so essentially nothing was getting rendered. I could not simply add a super call in `renderMTE`, as the chest has some special rendering and will not get rendered properly when called by `renderMTE`.

My one issue in solving this was that I now have to find some way to get `partialTicks` in `MetaTileEntityRenderer#renderBlock`, which is why I am adding this as a comment instead of making a PR directly. If anyone has any idea on how to find `partialTicks` or what number to pass in, please let me know.

**Comment by TheCodex6824** [comment] 2021-03-16 21:32
> My one issue in solving this was that I now have to find some way to get `partialTicks` in `MetaTileEntityRenderer#renderBlock`, which is why I am adding this as a comment instead of making a PR directly. If anyone has any idea on how to find `partialTicks` or what number to pass in, please let me know.

`Minecraft.getMinecraft().getRenderPartialTicks()` should work for 1.12, not sure about later versions. From what I gather about your observations, it looks like the chests not rendering was because the game expected TEs to render the FastTESR way but they weren't, am I understanding that properly?

**Comment by ALongStringOfNumbers** [comment] 2021-03-16 21:36
The chests not rendering was because the render block method called all renders to be done with one method, https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/render/MetaTileEntityRenderer.java#L116 

This call would force blocks that we IFastRenderMTEs to use this method as well, and in the case of the chest, this method is overriden but with an empty method body, meaning that it was not getting rendered at all.

**Comment by ALongStringOfNumbers** [comment] 2021-03-16 21:47
> `Minecraft.getMinecraft().getRenderPartialTicks()` should work for 1.12, not sure about later versions. 

Thanks for this heads up. I have started using this and now the chests open once again. This leaves some small things left to iron out because of how the chest rendering is done.

**Closed** 2021-04-05 16:27 UTC
Labels: status: unverified, type: bug
