### ISSUE TITLE
Forestry Integration broken (bottler Machine)

### ISSUE THREAD

**Issue by Zer0Lyfe** [GregTechCE/GregTech#22] opened 2018-04-14 09:12 UTC
Most if not all GT items are getting a recipe in the bottler from Forestry for some odd reason
There is examples of it happening:
![2018-04-14_17 04 43](https://user-images.githubusercontent.com/28994351/38766648-daaafcfc-4006-11e8-946f-0f1edde2c78f.png)
![2018-04-14_17 04 55](https://user-images.githubusercontent.com/28994351/38766649-dc4077fe-4006-11e8-9585-89dcdbcba43a.png)

**Comment by Archengius** [comment] 2018-04-14 09:13
it's known bag, caused by forestry. it's only visual jei bug, however.

**Comment by Archengius** [comment] 2018-04-14 09:14
and i can't see "forestry integration" here - it's just forestry thinks that every item which itemstack can have fluid capability is fluid container.

**Comment by Exidex** [comment] 2018-04-14 09:17
It's not fixed yet. So reopening

**Comment by mezz** [comment] 2018-04-14 23:09
I did some deep debugging and this is caused by items in the creative menu that have wildcard meta values.
These items come from gregtech and are located in the "search" and "gregtech.main" tabs.

I will add some checks in JEI to check for this and defend against it. Please check the items you add to the creative menu to make sure they have valid meta.

**Comment by mezz** [comment] 2018-04-14 23:31
I have added protections in JEI here: https://github.com/mezz/JustEnoughItems/commit/71d90b3f4001b742d6886fee476e1cab361e1632

Please make sure you do not use `OreDictionary.WILDCARD_VALUE` as a meta value for your items, they are interpreted in recipes and by JEI as wildcards that match all subtypes of that item.

**Comment by Archengius** [comment] 2018-04-15 06:58
But it worked properly in all other recipes, that's pretty weird.

**Comment by Exidex** [comment] 2018-04-15 20:54
Fixed in jei, and in eaa5516ab70f15975afaa914d7a1d1e3064bdca1

**Closed by Exidex** 2018-04-15 20:54 UTC
