### ISSUE TITLE
Tools Of All Materials Don't Work In Custom Recipes

### ISSUE THREAD

**Issue by EmosewaPixel** [GregTechCE/GregTech#335] opened 2018-09-29 09:23 UTC
Yes, this is a really weird issue. While recipes from GTCE and my addons that use crafting tool oredicts work fine, ones added with CraftTweaker don't work with every material.
For example I have this illumination plate recipe:
![image](https://user-images.githubusercontent.com/25333164/46243833-4e5efb80-c3d8-11e8-849b-c068ff47b064.png)
After the first recipe, Darmstandium tools stop working
![image](https://user-images.githubusercontent.com/25333164/46243839-5c148100-c3d8-11e8-8106-24592ce32ba1.png)
Iron tools work fine with any durability
![image](https://user-images.githubusercontent.com/25333164/46243854-85cda800-c3d8-11e8-96ba-730fc09b6ffb.png)
 I'm not sure whether it's world-specific, but on certain worlds in certain recipes I've had diamond and cobalt hammers not work in custom recipes. It's such a random bug.

**Comment by Rongmario** [comment] 2018-09-29 09:28
Whats the script lookin' like?

**Comment by EmosewaPixel** [comment] 2018-09-29 09:29
`
recipes.addShaped(<appliedenergistics2:part:180>*2,[
[<ore:craftingToolHardHammer>,<ore:plateGlowstone>,<appliedenergistics2:quartz_glass>],
[<ore:plateBlackSteel>,<ore:plateRedstone>,<appliedenergistics2:quartz_glass>],
[<ore:craftingToolWrench>,<ore:plateGlowstone>,<appliedenergistics2:quartz_glass>]
]);`

**Comment by Rongmario** [comment] 2018-09-29 12:27
More info: https://github.com/EmosewaPixel/GregBlock/issues/6

**Comment by Agrax** [comment] 2018-09-29 13:04
`recipes.addShaped(<foundry:machine>, [
	[brickFoundry, <foundry:bronzecauldron>, brickFoundry],
	[<ore:plateBronze>, refractoryCasingBasic, <ore:plateBronze>],
	[brickFoundry, <ore:craftingToolHardHammer>, brickFoundry]]);`

That one works just fine in Infitech 3.

Really, can't reproduce with any tool. That has to be some kind of an incompatibility issue

**Comment by Archengius** [comment] 2018-10-08 17:14
can't seem to reproduce. closing for now.

**Closed by Archengius** 2018-10-08 17:14 UTC
Labels: (●__●)
