### ISSUE TITLE
[BUG] Crash when attempting to add a GTCE axe to Enderio Farming Station

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1192] opened 2020-08-11 11:23 UTC
**Describe the bug**
The game crashes when shift click a Darmenstadium axe into the Ender io farming station

**Versions**
Forge: 
GTCE: 1.9.3.531
Ender io: 5.1.55
Endercore: 1.12.2-0.5.73
Enderio Endergy: 5.1.55
_Modpack:_ Omnifactory development environment, based on update fork found here: https://github.com/OmnifactoryDevs/Omnifactory/pull/505

**Setup**
Playing Solo (Only tested solo)

**Steps To Reproduce**
1) Grab an Ender io farming station and a Darmenstadium axe from JEI
2) Place the farming station, open the GUI, and shift click the axe in

**Expected behavior**
No crash, and the tool does not go into the farming station (as tools were blacklisted from fake player behavior in b7c6984 )

**Additional context**
Crash report found here: https://pastebin.com/YitHkWma

**Comment by Saereth** [comment] 2020-08-12 12:38
I can definitely verify this issue exists, I've even looked into the code for it on gtce and enderios' side and its absolutely gtce causing the crash, it would require a minor rewrite with just some basic sanity checking in the get tool type override to fix as a quick fix.I didnt have time to actually write a fix though unfortunately. 


https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/items/toolitem/ToolMetaItem.java#L254

this should just return -1 on null blockstate instead of the precondition check which leads to the crash. This wont make it WORK with enderio as gtce still needs a valid blockstate to tell if the tool can properly mine the block but it will prevent the crash. Alternatively if no block state is supplied you could default it to 1 or some higher number which should allow it to work but wont be directly checking the tool mining level on a per block basis (this is more enderio's implementation issue that gtces).

Either way to prevent the crash is a pretty simple code edit

**Comment by LAGIdiot** [comment] 2020-08-12 17:24
Thank you for reporting this issue.

**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.3 (dev build on 7ee52df7ee0194fdf89e35c8c36e478dbf2b7360)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed

**Additional info:**
Crash is definitively caused by GTCE. As we are incorrectly imposing not null check on nullable param. So crash will be fixed.
But regarding making GTCE tools work in EnderIO machines there is nothing we can do on our side. As we require `IBlockState` to properly evaluate if block can be mined by our tools which EnderIO does not provides.

**Closed** 2020-08-17 19:02 UTC
Labels: status: accepted, type: bug, type: multi mod interaction
