### ISSUE TITLE
[BUG] GregTech v1.17.1.770 - Crash while Initialization phase

### ISSUE THREAD

**Issue by VodaVodichka** [GregTechCE/GregTech#1745] opened 2022-07-04 16:42 UTC
**Describe the bug**
Just a crash while loading Minecraft 1.12.2 with my modpack

**Versions**
Forge: 14.23.5.2860
GTCE: 1.17.1.770

**Setup**
Playing Solo

**Steps To Reproduce**
1) I just ran Minecraft
2) And then it crashed

**Expected behavior**
Check the crash-report file for more information
[crash-2022-07-04_19.31.23-client.txt](https://github.com/GregTechCE/GregTech/files/9041083/crash-2022-07-04_19.31.23-client.txt)

Besides, I checked the 1.8.4.419 version, and I saw the same thing

**Comment by warjort** [comment] 2022-07-05 02:27
Duplicate of #1698

Probably dynamic lights issue.

**Comment by serenibyss** [comment] 2022-07-05 05:35
Closing as duplicate

**Closed as completed by serenibyss** 2022-07-05 05:35 UTC
Labels: type: bug, status: unverified
