### ISSUE TITLE
Wrong position of chests

### ISSUE THREAD

**Issue by 15103875d** [GregTechCE/GregTech#655] opened 2019-03-17 18:15 UTC
As the graph shows, the bronze chest doesn't locate in its original position.

![06](https://user-images.githubusercontent.com/43509783/54495892-76f59600-4923-11e9-8b9d-839b448c885a.jpg)
The bronze chest moves to its right automatically

![05](https://user-images.githubusercontent.com/43509783/54495896-778e2c80-4923-11e9-950d-dcb688e52b18.jpg)
When I open it, the chest on the right seems opened

![07](https://user-images.githubusercontent.com/43509783/54495895-778e2c80-4923-11e9-9a52-d0abf8827cbb.jpg)
There are 2 steel chests under the wood one. But they are hidden.

**Comment by Archengius** [comment] 2019-03-17 18:17
do you have any graphics-related mods?

**Comment by 15103875d** [comment] 2019-03-17 18:26
> do you have any graphics-related mods?

No

**Comment by 15103875d** [comment] 2019-03-18 01:35
Back to normal when I restart the client.

**Comment by Archengius** [comment] 2019-03-18 08:54
cannot reproduce, do you have any better instructions?
i'm mostly sure one of mods in your modpack is causing that

**Comment by 15103875d** [comment] 2019-03-18 16:52
Many thanks. Maybe not a bug. It does appear anymore.

**Comment by Shadows-of-Fire** [comment] 2019-03-26 01:20
I'm seeing it happen in FTB Interactions, the chest is offset to some degree ![](https://i.imgur.com/Z6GMYXM.png)
(Those chests are near that TE machine)

**Comment by Shadows-of-Fire** [comment] 2019-03-26 01:22
This would be resolved by adding a call to `GlStateManager.pushMatrix()` as the first line in [this method](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/render/ChestRenderer.java#L52) and adding a call to `GlStateManager.popMatrix()` as the last line.

**Comment by Archengius** [comment] 2019-03-27 12:29
@Shadows-of-Fire no it would NOT be resolved in using GL State in fast TESR like that

**Comment by Archengius** [comment] 2019-03-27 12:34
So far i cause no translations in my renderers, neither CCL does. It's some other mod behaving wrongly with fast TESR.

**Closed by Archengius** 2019-03-27 12:34 UTC
