### ISSUE TITLE
Machines and Wires placed with fill command are transparent.

### ISSUE THREAD

**Issue by CentAtMoney** [GregTechCE/GregTech#1153] opened 2020-07-18 20:05 UTC
When placing machines or wires with the fill command, the blocks are placed but seem to render incorrectly as transparent blocks. The blocks also can't be interacted with and when broken cause other machines and wires to become black opaque cubes.
To reproduce try placing a gregtech machine via `/fill <pos1> <pos2> gregtech:machine <valid id>`.

Here is a screenshot where I placed a bronze boiler with my hand and a bronze boiler via /fill 
![2020-07-18_15 56 57](https://user-images.githubusercontent.com/38444344/87860950-a4839280-c90f-11ea-98bc-9c88f2a1fed9.png)
Also note that machines that become black cubes are not rendered properly until after a complete game restart.

**Comment by LAGIdiot** [comment] 2020-07-25 07:35
**Version:**
Forge: 14.23.5.2847
GTCE: 1.9.2 (dev build on 9c11e39)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed

**Conclusion:**
I am closing this as **wont fix** because we are not able to fix this without complete rewrite of our machine registration system. Which would be tremendous amount of work that would made all previous saves incompatible. And that is no no for us.

**Additional Notes:**
You can spawn most maybe even all other block (except machine based, cable/wire based, pipe based blocks) with this.

**Closed by LAGIdiot** 2020-07-25 07:35 UTC
