### ISSUE TITLE
[Bug] Machines&Cables go invisible when breaking something connected to alot of cables/machines

### ISSUE THREAD

**Issue by TheonlyTazz** [GregTechCE/GregTech#578] opened 2019-02-17 21:14 UTC
#### Issue Description:
Game doesnt render any Gregtech related block after breaking a machine or cable.
happens rather randomly so i cant exactly reproduce.
does happen more often whenever multiple machines are connected to a certain amount of cables

Only fix is to restart client.

#### Steps to reproduce:
1.Break Cable
2.Machines and cables go invisible
3. ????
...
5. Restart Minecraft

#### Affected Versions (Do _not_ use "latest"):
*Gregtech Community Edition:
1.12.2-1.5.17.167

* Minecraft:
  1.12.2
* Forge:
  Forge-14.23.5.2795
* SpongeForge?
  no
* Optifine?
  no
* Single Player and/or Server?
  Server

![image](https://user-images.githubusercontent.com/3908847/52919272-f67e4e00-3300-11e9-85ea-e48f1e35ef05.png)

how it should look like:
![image](https://user-images.githubusercontent.com/3908847/52919305-5b39a880-3301-11e9-91b1-a309cecffb76.png)

**Comment by roboderpy** [comment] 2019-02-17 23:57
Duplicate of https://github.com/GregTechCE/GregTech/issues/566

**Comment by Rongmario** [comment] 2019-02-22 09:36
This is definitely not a duplicate of #566 lmao

**Comment by roboderpy** [comment] 2019-02-22 09:38
This is caused by TileEntity reappear on client (thanks, Mojang) after being broken by local player, it is duplicate of #566

**Comment by Archengius** [comment] 2019-05-02 22:11
no idea what is that and it won't be fixed

**Closed by Archengius** 2019-05-02 22:11 UTC
