### ISSUE TITLE
[BUG] Methane Positive crafting loop possible

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1329] opened 2020-11-28 04:42 UTC
**Describe the bug**
A Methane positive crafting loop exists, such that with the addition of solely water, infinite methane and oxygen can be generated.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.7.594
_Modpack:_ None
_Addons:_ None

**Setup**
Playing Solo
_New world generated_ Yes

**Steps To Reproduce**
1) Make Methane in a Chemical Reactor via the recipe: 1 Carbon dust + IC:0 + 4k mB of Hydrogen -> 5k mB Methane
2) In a Chemical Reactor, use the recipe: IC:1 + 1k mB Methane + 2k mB Water -> 8k mB Hydrogen + 1k mB CO2.
3) In an Electrolyzer, break down the CO2 -> 1 Carbon dust + 2k mB Oxygen.
4) A methane and oxygen positive infinite loop presents itself due to the input amount of Methane in step 2 and the output amount of Hydrogen in step 2

**Expected behavior**
No positive infinite loop for methane and oxygen should exist. Solving this would most likely involve adjusting the Chemical Reactor recipe present in Step 2 outlined above or by adjusting the Methane output in the recipe outlined in Step 1.

**Comment by Exaxxion** [comment] 2020-11-28 05:10
This is one of several recipes where GTCE isn't sure whether to handle mols of fluids like a fluid or an item. Frequently fluids are 1B = 1mol and items are N dusts = 1mol, where N is sum of individual constituents.

The methane generation recipe at issue here produces 5B of output like an item (4 mol of hydrogen and 1 mol carbon) whereas it should behave like fluids and produce 1mol of output as 1B.

The water chemical reactor recipe is strange on its own; it's the inverse of the Sabatier reaction which at 400C and at pressure exothermically turns `CO2 + 4H2 -> CH4 + 2H2O`. It's a nice recipe from a gameplay standpoint since it lets you get hydrogen out of methane gleaned from distilling petroleum, but I'm not sure that such a reaction is possible in reality.

Typically what would be done to process natural gas is Steam Methane Reforming. This process involves mixing methane (typically in the form of natural gas) with steam to produce syngas via the reaction `CH4 + H2O ⇌ CO + 3 H2`. You would then employ the water-gas shift reaction with steam to get additional hydrogen: `CO + H2O ⇌ CO2 + H2`.

**Comment by LAGIdiot** [comment] 2020-12-05 09:12
Thank you for reporting this issue. I accept that Methane positive loop exists and should be fixed. But regarding way how to fix it I am not sure. As mentioned in second post we may need to give crafting with liquids more serious look up as there may be more problems regarding it. Also I am not chemists so it may take some time to get it in my head.

**Comment by Exaxxion** [comment] 2020-12-07 12:10
I'll try to clarify a bit: "mol" is an SI unit used in balancing chemical equations (stoichiometry). Moles are a measure of "amount of substance" with a formal definition but it's good enough for our purposes to abstract it to "units of a specific thing."

Equations consist of moles of reactants in an appropriate ratio to produce moles of products. In this case, the equation `CO2 + 4H2 -> CH4 + 2H2O` can be read as "one mole of carbon dioxide reacts with four moles of hydrogen to produce one mole of methane and two moles of water."

One complicating factor is that hydrogen naturally appears as molecules composed of two of the same atom, so in-game this would be represented as 8 units of hydrogen, not 4. This is also true of Nitrogen, Oxygen, Fluorine, and Chlorine, so care must be taken to multiply the units in-game appropriately when transposing chemical equations into recipes.

For fluids, mostly it is the case that a mole of fluids is one bucket of that fluid (with the exception of molten ingots, which operates on the 144mB to an ingot convention). The above formula for example would be represented in-game as 1B Carbon Dioxide + 8B Hydrogen => 1B Methane + 2B Water. Using this convention, electrolysis (where recipes are deemed appropriate) would always split 1B of a fluid into its constituent moles of items and fluids.

Items get a little more tricky because the convention is that a mole of a solid substance is a number of dusts equal to the sum of its components. For example, Magnesium Chloride is noted as `MgCl2` in-game. Since it is composed of one Magnesium and two Chlorine, a mole of it is 3 dusts. This complicates the math a little when you mix liquids and items in chemical reactions because you have to multiply the number of dusts accordingly. Continuing with the MgCl2 example, the EBF recipe for making titanium uses 1B TiCl4 and 2 Mg dusts to produce 1 titanium ingot and 6 MgCl2 dusts (which is two moles). This conforms with the balanced equation `TiCl4 + 2 Mg -> Ti + 2 MgCl2`

I think these conventions are fine, and the issue is merely that there are certain recipes which deviate from them, resulting in positive feedback loops by abusing the imbalanced ratios (specifically that I recall: Phosphorous Pentoxide, Methane).

**Closed** 2021-01-26 19:50 UTC
Labels: status: help needed, type: bug
