### ISSUE TITLE
Crash reports every second regarding surface rock materials when using Minecraft default terrain generation

### ISSUE THREAD

**Issue by AstherLC** [GregTechCE/GregTech#1069] opened 2020-04-23 19:07 UTC
[crash-2020-04-19_20.59.49-client.txt](https://github.com/GregTechCE/GregTech/files/4524675/crash-2020-04-19_20.59.49-client.txt)

I'm using version 1.9.1.501, I erased the previous gregtech config file to see if that was the mistake but I keep getting the errors. The game can be played but I got like 100 of those files on 2 minutes of play time. They all seem to look the same.

**Comment by LAGIdiot** [comment] 2020-04-23 19:33
I go through crash log and I have 4 things to discuss.

1. Version which you are writing that you are using is not same as one reported in crash log. Are you sure you are using right version?
2. I don't see anything related to surface rocks. Can you please point me to it?
3. Crash log does not state from which mode crash comes and GTCE is not only one installed. Did you reported to other mods too?
4. Crash log shows that problems occurred when constructing **gtadditions**. Shouldn't you go first to that mod?

Please provide answers to my questions so I can move on with investigation.

**Comment by AstherLC** [comment] 2020-04-23 19:52
[crash-2020-04-23_14.48.40-client.txt](https://github.com/GregTechCE/GregTech/files/4524865/crash-2020-04-23_14.48.40-client.txt)
I uploaded the wrong crash report, sorry for that. This is the one

**Comment by LAGIdiot** [comment] 2020-04-23 21:06
Yep, that looks exactly like surface rock crash on latest build. I will take look at it later.

**Comment by LAGIdiot** [comment] 2020-04-24 15:25
**Version:**
1.9.1 (dev build on e3668e38c3bb77e74479d78425558e37d2dc0257 same source as version 1.9.1.501)

**Environment:**
GTCE dev; new world generated; default world gen

**Outcome:**
Unable to reproduce. 

Please provide information when and with which version was world created. Was GTCE data for worldgen edited in any way? Also it seems that you have vanilla fix installed which may be interfering with NBT system. Please uninstall it first and try on new world.

**Comment by AstherLC** [comment] 2020-04-24 18:53
[report.txt](https://github.com/GregTechCE/GregTech/files/4530869/report.txt)
After removing VanillaFix the game doesn't give crash files, but MultiMC gives these messages that have the same text as the crash log, every second. 

I tested erasing the config file and opening my game with the GTCE version from Curseforge (1.9.0.481) and the MultiMC log doesn't show anything wrong.

I'm creating new worlds everytime I try this tests, and the GTCE config data is clean too. I'm erasing  and letting them generate each time just to make sure the problem is not related to that.

**Comment by LAGIdiot** [comment] 2020-04-25 07:21
**Version:**
gregtech-1.12.2-1.9.1.501; forge-1.12.2-14.23.5.2854

**Environment:**
Twitch Launcher; new world generated; default world gen

**Outcome:**
Bug confirmed.

**Additional notes:**
Surface rocks are generated correctly. After save load all Surface rocks are aluminium with same exactly same look. After first "touching" them they change it's look random surface rock formation. Material still aluminium.

Error descriptions is pointing to problem with different build/run version of underlying lib (most likely forge) additional investigation needed.

**Comment by LAGIdiot** [comment] 2020-04-25 12:46
**Proposed solution:**
Use latest official version of Forge: 1.12.2 - 14.23.5.2847.

**Additional notes:**
Last three specific versions were produced after official drop of MC 1.12 Forge support. They were build with new template which is not compatible with official Gradle build pipeline.

**Comment by LAGIdiot** [comment] 2020-06-08 16:48
Fixed by #1093.

**Closed by LAGIdiot** 2020-06-08 16:48 UTC
