### ISSUE TITLE
Batteries in buffers don't discharge evenly

### ISSUE THREAD

**Issue by TDSSS** [GregTechCE/GregTech#917] opened 2019-07-15 13:56 UTC
I will preface this by saying I am not entirely sure this isn't intended, as I was unable to find documentation for CE, but I know in GT5 batteries are supposed to discharge concurrently, not sequentially, and assume the same holds true unless given information to the contrary.

The situation is as follows: I have an x4 LV battery buffer connected to 4 LV steam turbines that is outputting to a LV to MV transformer. In theory the buffer should be getting enough power to keep the transformer going, but in practise the following happens:

The four batteries inside the buffer do not discharge evenly, instead the fourth battery is drained completely while the others fluctuate around nearly full, once that happens the connected machines stutter. It is always the last battery that gets drained first while the other batteries are mostly full, see:
![Capture](https://user-images.githubusercontent.com/32099540/61221267-6bbb4700-a718-11e9-9d0e-0344d0a9b6cc.PNG)

If I go ahead and swap the empty battery with one of the other three, it starts to charge while the battery in the last slot rather quickly discharges.

Issue occured on gregtech 1.8.3.146
(also using Shadows of Greg 1.12.2-2.8.0 in case that might be relevant)

**Comment by pyure** [comment] 2019-07-16 16:21
I believe this is deliberate, or at least not a problem.  The key thing is that the Amperage of the buffer appears to be based on the number of batteries, NOT the number of batteries-with-energy.

**Comment by Blood-Asp** [comment] 2019-07-16 16:28
i have to test to make sure it is really so, but afaik this is a problem.
The batteries themselfs have an limited de/charging speed. So if a buffer has 2 full and 14 empty batteries while not getting charged from outside, it could only supply 2 amp since it could not decharge from the batteries fast enough.
same with charging.

I know the CEU addon certainly suffers from this und i would expect they just reused the battery buffer code.

**Comment by Archengius** [comment] 2019-08-11 01:03
I can confirm battery buffers don't suffer from that in any way

**Comment by josiah-roberts** [comment] 2019-09-10 04:56
I can confirm that battery buffers *do* suffer from that.

My grid stops working (can only emit 1 amp, machines run out of power) when all but one battery is empty. Replace an empty battery with a full one, and downstream systems start working again.

**Comment by Divran** [comment] 2019-09-10 17:48
Did some tests, battery buffers do appear to only output amps equal to the amount of batteries which have any amount of charge.

**Comment by pyure** [comment] 2019-09-10 17:51
Yikes I was wrong :( That's really less fun than I thought.

**Comment by Archengius** [comment] 2019-09-15 09:08
Fixed in latest

**Closed by Archengius** 2019-09-15 09:08 UTC
