### ISSUE TITLE
An error is reported on the catserver server, and the surface rock cannot be loaded

### ISSUE THREAD

**Issue by zhangziming666** [GregTechCE/GregTech#1123] opened 2020-07-02 23:55 UTC
[07:44:07] [Server thread/ERROR]: A TileEntity gregtech:surface_rock(gregtech.common.blocks.surfacerock.TileEntitySurfaceRock) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.IllegalAccessError: tried to access field net.minecraft.nbt.NBTTagList.field_74747_a from class gregtech.common.blocks.surfacerock.TileEntitySurfaceRock
        at gregtech.common.blocks.surfacerock.TileEntitySurfaceRock.func_145839_a(TileEntitySurfaceRock.java:68) ~[TileEntitySurfaceRock.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:128) [avj.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:498) [aye.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) [ChunkIOProvider.class:git-CatServer-1.12.2-de0a1c1]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:151) [ChunkIOExecutor.class:git-CatServer-1.12.2-de0a1c1]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:776) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:630) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

Hope it can be fixed

**Comment by LAGIdiot** [comment] 2020-07-03 08:01
This seems as duplicate of #1122 which was already answered.

**Comment by LAGIdiot** [comment] 2020-07-11 16:18
Closed as duplicate to #1122

**Closed by LAGIdiot** 2020-07-11 16:18 UTC
Labels: type: duplicate
