### ISSUE TITLE
Amps may not be burning up wires

### ISSUE THREAD

**Issue by Lilylicious** [GregTechCE/GregTech#890] opened 2019-07-04 10:17 UTC
Recreating the issue because the previous one was closed due to lack of version number.

One sentence summary: It appears that cables do not burn up when they have too many amps running through them.

Assumptions: Diesel Generators produce 1A each. CEU's accept 2A per battery slot. (Based on GT5).

I'm able to use 16 [tier] generators for a single 16 slot [tier] CEU. All 16 generators can use a single line of 1x HV cable, regardless of amp limit.

Using a [tier+1] CEU allows 64 [tier] generators, all of which still work on a single line of 1x cables.

Assuming that generators should generate 1A, something is wrong. Might be an issue with amperesUsed in AcceptEnergyFromNetwork or DispatchEnergyToNode

I was measuring the power output of the CEU using a power monitor from Ender IO, and I was dumping everything into an energy trash can, so the CEU was not filling up and disabling generators.

Version: gregtech-1.12.2-1.8.4.419.jar

**Comment by Lilylicious** [comment] 2019-07-04 17:28
Through further testing, I've determined that the issue is with the CEU. Feeding consumers with low-thickness cables does burn them as expected. That said, it really doesn't make sense that you can feed unlimited amps through any cable into a CEU.

**Comment by Archengius** [comment] 2019-07-05 07:03
duplicate of #870

**Closed by Archengius** 2019-07-05 07:03 UTC
