### ISSUE TITLE
[BUG] Minecraft Furnace can not be crafted.

### ISSUE THREAD

**Issue by Alendill** [GregTechCE/GregTech#1618] opened 2021-05-24 16:18 UTC
Minecraft furnace, brick can not be crafted normally. Please check it. Thanks

This is the Only One way to craft a furnace.
![20210525091055](https://user-images.githubusercontent.com/40451613/119425624-54007100-bd3a-11eb-8a63-2f3ae46bacef.png)

This is brick.
![20210525001710](https://user-images.githubusercontent.com/40451613/119426080-2e279c00-bd3b-11eb-8b25-05135932addd.png)

This is my mods directory.
![20210525091122](https://user-images.githubusercontent.com/40451613/119425633-595dbb80-bd3a-11eb-8c20-214d28e18a1a.png)

**Comment by DoctorWeirdGuy** [comment] 2021-05-24 20:56
Are you sure that this is caused by GTCE and not some other mod/recipe change? Are you playing a pack or something?

**Comment by Alendill** [comment] 2021-05-25 01:18
[https://github.com/Alendill/MarkDownImages/blob/master/20210525091055.png?raw=true](url)
this is the Only One way to craft a furnace.

this is my mods directory.

[https://github.com/Alendill/MarkDownImages/blob/master/20210525091122.png?raw=true](url)

**Comment by DStrand1** [comment] 2021-05-25 02:00
There were issues with some autogenerated recipe code in Gregicality for that release, it is fixed in the latest release.

**Closed by DStrand1** 2021-05-25 02:00 UTC
Labels: status: unverified, type: bug
