### ISSUE TITLE
[BUG] Input Hatch causes fluid containers to overflow with water

### ISSUE THREAD

**Issue by thedeadferryman** [GregTechCE/GregTech#1446] opened 2021-02-06 00:07 UTC
**Describe the bug**
Fluid input hatch (HV in my case) causes fluid container (IC2exp Iridium Tank in my case) to overflow, i.e. to have nearly infinite water amount (2147...647mb, when max for that container is 1024000mb) when the container is placed near the hatch without any pipes. 
The hatch itself is a part of a steel boiler.

**Versions**
Forge: 14.23.5.2854
GTCE: 1.11.1.632
_Addons:_
CEU: 1.0.4.3

**Setup**
Playing multiplayer
_New world generated_ if applicable

**Steps To Reproduce**
1) Build Large Steam Boiler with two fluid input hatches
2) Put some fuel into the boiler
3) Place Iridium Tank (IC2) full of water in front of input hatch

**Screenshots**
![image](https://user-images.githubusercontent.com/25135166/107101465-796b7c80-6828-11eb-8598-0eca32e1fd36.png)

**Comment by Archengius** [comment] 2021-02-06 00:24
I'm 99% sure it's IC2 bug, because input hatches do nothing but pull liquid from nearby containers though standard forge API methods, and so far that has never been an issue with any other tank.

**Comment by DStrand1** [comment] 2021-02-06 01:14
I think it is as well, but since I changed some of the Input Hatch code in the last GT release, I am going to thoroughly test this before we close it.

**Comment by DStrand1** [comment] 2021-02-06 01:23
I can confirm that this issue is only present with IC2 tanks. Tested against GT tanks, and tanks from many popular mods (Thermal Expansion, EnderIO, Mekanism, XU2) and no issues were present.

**Closed** 2021-02-06 01:29 UTC
Labels: status: unverified, type: bug
