### ISSUE TITLE
[BUG] The Crafting Station's Storage tab fails with the Forestry Worktable

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GregTechCE/GregTech#1239] opened 2020-09-13 05:33 UTC
**Describe the bug**
Using the Storage Tab of the Crafting Station to store items in adjacent inventories works fine, however when using adjacent to a Forestry Worktable, which allows item input but not extraction, the items added via the storage tab and transferred to the Forestry Worktable will essentially be stuck, because they cannot be extracted. These items are still visible in the Storage Tab, but they cannot be interacted with in any manor.

**Versions**
Forge: 14.23.5.2847
GTCE: 1.10.1.557
Forestry: 5.8.2.422
_Modpack:_ Omnifactory development testing on the updateGTCE branch
_Addons:_ SoG 2.14

**Setup**
Playing Solo (only tested solo)
_New world generated_ Yes

**Steps To Reproduce**
1) Place a Crafting Station next to a Forestry Worktable and no other adjacent inventories
2) Add items via the Storage tab of the Crafting Station
3) See that the added items are put in the Forestry Worktable and are still visible in the Storage tab
4) Attempt to extract the items from the Storage tab and fail.

**Expected behavior**
Since the Forestry Worktable does not allow items to be pulled from it by default, it might be easiest to blacklist this inventory from having items stored in it via the Storage tab. This prevents items being stuck in the inventory. Or if possible maybe a check on the adjacent inventory to see if it allows extracting before items are added to it via the Storage tab

**Screenshots**
Screenshot of items not able to be extracted from the Forestry Worktable
![2020-09-12_22 31 27](https://user-images.githubusercontent.com/31759736/93011076-f62f4e80-f547-11ea-98b8-9acfa7677ace.png)

**Comment by TheXTrunner** [comment] 2020-09-13 05:54
I think I had this happened with an obsidian chest too, iron chests

**Comment by LAGIdiot** [comment] 2020-09-17 18:47
Thank you for reporting this issue.

**Version:**
Forge: 14.23.5.2847
GTCE: 1.10.1 (dev build on a53edbe7d1cf42fd101464f50c580a3d73349015)

**Enviroment:**
GTCE dev

**Outcome:**
Bug confirmed

**Implementation notes:**
On placing of Crafting Station and `NeighborChange` check if connected can be used to extract items from it. If not don't add it to list of connected inventories.

**Comment by fmarceau** [comment] 2020-10-30 02:04
I will have a look at this one

**Comment by fmarceau** [comment] 2020-10-31 00:08
@LAGIdiot in the case of a non-empty inventory, it would be possible to do an extractItem(simulate = true) but if the latter is empty, there is no way to check if it could eventually be extracted from. If you want, I can add a simulated extraction for non-empty inventories and not make the connection if it fails but I don't see what could be done in the case of an empty one. Any idea?

**Comment by LAGIdiot** [comment] 2020-10-31 09:50
I have quickly checked how this behaves and I don't see any 100% solution for it. But I think we can cheat our way out of this. There is quite few things we need to do to make this work and it will probably blow scope of this issue way up.

1. Let's add info to **Storage** tab that says something like "Available items from connected inventories that can be used for crafting"
2. Let's show only items that can be used in **Storage** tab
    This will probably need to be handled by `ItemSource` level by show only items that can be extracted which means that this will have to be updated on every change in given connected inventory
    Checking should be done by using **extract with simulate=true**
3. Let's change priorities of connected inventories
    This has to become **dynamic**
    Priorities (from high to low): inventory we can extract from (there is something we tested), empty inventories which does not use `ISidedInventory`, Crafting Station inventories, empty inventory with `ISidedInventory` handler (maybe I would rather not even include these)
4. Let's change priority to which inventory are items stores / taken from
    Items will be taken firstly from inventory with few of them with intent to clear that inventory
    Items will be put in inventory in which they are already first, then to empty inventory based on priority
        Items will be put in inventory where is most of them (with intent to fill it up) but with exception if it is Crafting Station itself (in this case they will be put in place with second most)

This is definitely not implementation guide but only my input to discussion.

**Comment by fmarceau** [comment] 2020-10-31 16:01
I like the overall plan. Very few inventories are non-extractable in the game anyway so I guess we can safely accept a non-perfect solution.

**Comment by fmarceau** [comment] 2020-10-31 18:02
Items 1 and 2 are done; now working on 3 and 4.

@LAGIdiot what would the pros and cons be of allowing insertion / extraction of empty inventory using ISidedInventory?

**Comment by LAGIdiot** [comment] 2020-11-01 07:50
Regarding `ISidedInventory` I feel somehow distressful when working with it because it is way different from other inventory management interfaces and nearly every problem with inventory I was fixing was related to it.
pros: we will have better range of inventories we can interact with (not sure about ratio against other implementations)
cons: we may encounter situation in which we will insert items to it and "lose them" as we will find out that we can't extract them back

**Comment by fmarceau** [comment] 2020-11-01 17:10
As it's been commented out to me on Discord, there aren't much of those non-extractable inventories. We might add those checks as you described them previously and use a blacklist, which would initially contain the Forestry Worktable, for empty inventories.

@LAGIdiot regarding the prioritization that you were recommending, the problem is that it would probably conflict with the current priority system (which seems to be used for shift-clicking item back into the tool inventory or things like that). Hence why I had submitted a PR which is only partially solving the problem here.

**Comment by LAGIdiot** [comment] 2020-11-02 21:55
Sure we can take prioritization out as it is out of scope, put it in new issue and give it another few rounds of refining.

Blacklisting does not sound as bad idea if we make it configurable through `ConfigHolder` and globally available (as this inventory system has potential for wider use).

**Comment by LAGIdiot** [comment] 2020-11-08 12:50
As we won't be able to handle this item at once, given complexity of required proper solution. I had split some work from this one to #1302 where will handled interaction with other inventories. And this one will be mitigated by #1290 in it's current scope. This is not full size fix but it is best we can get out right now.

**Closed** 2020-11-23 17:14 UTC
Labels: status: accepted, status: help needed, type: bug
